/**
 * Token Compilation Pipeline
 * Reads design-tokens/tokens.json and generates:
 *   - src/styles/tokens.css (CSS custom properties for dark + light themes)
 *   - src/lib/tokens.ts (TypeScript constants module)
 */
import { readFileSync, writeFileSync, mkdirSync } from "fs";
import { resolve, dirname } from "path";

const ROOT = resolve(dirname(new URL(import.meta.url).pathname), "..");
const TOKENS_PATH = resolve(ROOT, "design-tokens/tokens.json");
const CSS_OUT = resolve(ROOT, "src/styles/tokens.css");
const TS_OUT = resolve(ROOT, "src/lib/tokens.ts");

interface TokenValue {
  $value: string | number;
  $description?: string;
}

const raw = JSON.parse(readFileSync(TOKENS_PATH, "utf-8"));

function extractValues(obj: Record<string, TokenValue>): Record<string, string> {
  const result: Record<string, string> = {};
  for (const [key, val] of Object.entries(obj)) {
    if (val && typeof val === "object" && "$value" in val) {
      result[key] = String(val.$value);
    }
  }
  return result;
}

const darkColors = extractValues(raw.color.dark);
const lightColors = extractValues(raw.color.light);
const stageColors = extractValues(raw.color.stage);
const spaces = extractValues(raw.space);
const radii = extractValues(raw.radius);
const fontSizes = extractValues(raw.fontSize);
const lineHeights = extractValues(raw.lineHeight);
const fontFamilies = extractValues(raw.fontFamily);
const fontWeights = extractValues(raw.fontWeight);
const motions = extractValues(raw.motion);



// Build CSS
const cssLines: string[] = [
  "/* Auto-generated by scripts/compile-tokens.ts — DO NOT EDIT */",
  "",
  ":root {",
  "  /* Colors — Dark (default) */",
  ...Object.entries(darkColors).map(([k, v]) => `  --color-${k}: ${v};`),
  "",
  "  /* Stage colors */",
  ...Object.entries(stageColors).map(([k, v]) => `  --color-stage-${k}: ${v};`),
  "",
  "  /* Spacing */",
  ...Object.entries(spaces).map(([k, v]) => `  --spacing-${k.replace(".", "_")}: ${v};`),
  "",
  "  /* Border radius */",
  ...Object.entries(radii).map(([k, v]) => `  --radius-${k}: ${v};`),
  "",
  "  /* Font families */",
  ...Object.entries(fontFamilies).map(([k, v]) => `  --font-${k}: ${v};`),
  "",
  "  /* Font sizes */",
  ...Object.entries(fontSizes)
    .filter(([k]) => k !== "$root")
    .map(([k, v]) => `  --text-${k}: ${v};`),
  "",
  "  /* Line heights */",
  ...Object.entries(lineHeights).map(([k, v]) => `  --leading-${k}: ${v};`),
  "",
  "  /* Font weights */",
  ...Object.entries(fontWeights).map(([k, v]) => `  --font-${k}: ${v};`),
  "",
  "  /* Motion */",
  ...Object.entries(motions).map(([k, v]) => `  --duration-${k}: ${v};`),
  "  --ease-reveal: ease-out;",
  "}",
  "",
  "/* Light theme override */",
  '[data-theme="light"] {',
  ...Object.entries(lightColors).map(([k, v]) => `  --color-${k}: ${v};`),
  "}",
  "",
];

mkdirSync(dirname(CSS_OUT), { recursive: true });
writeFileSync(CSS_OUT, cssLines.join("\n") + "\n");

// Build TS
const tsLines: string[] = [
  "/* Auto-generated by scripts/compile-tokens.ts — DO NOT EDIT */",
  "",
  "export const colors = {",
  "  dark: {",
  ...Object.entries(darkColors).map(([k, v]) => `    "${k}": "${v}",`),
  "  },",
  "  light: {",
  ...Object.entries(lightColors).map(([k, v]) => `    "${k}": "${v}",`),
  "  },",
  "  stage: {",
  ...Object.entries(stageColors).map(([k, v]) => `    "${k}": "${v}",`),
  "  },",
  "} as const;",
  "",
  "export const space = {",
  ...Object.entries(spaces).map(([k, v]) => `  "${k}": "${v}",`),
  "} as const;",
  "",
  "export const radius = {",
  ...Object.entries(radii).map(([k, v]) => `  "${k}": "${v}",`),
  "} as const;",
  "",
  "export const fontSize = {",
  ...Object.entries(fontSizes).map(([k, v]) => `  "${k}": "${v}",`),
  "} as const;",
  "",
  "export const lineHeight = {",
  ...Object.entries(lineHeights).map(([k, v]) => `  "${k}": "${v}",`),
  "} as const;",
  "",
  "export const fontFamily = {",
  ...Object.entries(fontFamilies).map(([k, v]) => `  "${k}": "${v}",`),
  "} as const;",
  "",
  "export const fontWeight = {",
  ...Object.entries(fontWeights).map(([k, v]) => `  "${k}": ${v},`),
  "} as const;",
  "",
  "export const motion = {",
  ...Object.entries(motions).map(([k, v]) => `  "${k}": "${v}",`),
  "} as const;",
  "",
  "export type ColorToken = keyof typeof colors.dark;",
  "export type SpaceToken = keyof typeof space;",
  "export type RadiusToken = keyof typeof radius;",
  "",
];

mkdirSync(dirname(TS_OUT), { recursive: true });
writeFileSync(TS_OUT, tsLines.join("\n") + "\n");

console.log("✓ tokens.css written to", CSS_OUT);
console.log("✓ tokens.ts written to", TS_OUT);
