#!/usr/bin/env node
/**
 * Token Compilation Pipeline
 * Converts design-tokens/tokens.json → src/styles/tokens.css + src/lib/tokens.ts
 * Generates CSS custom properties and TypeScript constants for both dark and light themes.
 */
import { readFileSync, writeFileSync, mkdirSync } from 'fs';
import { dirname, resolve } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = resolve(__dirname, '..');
const tokens = JSON.parse(readFileSync(resolve(root, 'design-tokens/tokens.json'), 'utf-8'));

function extractValue(obj) {
  if (obj && typeof obj === 'object' && '$value' in obj) return obj.$value;
  return obj;
}

function flattenTokens(obj, prefix = '') {
  const result = {};
  for (const [key, value] of Object.entries(obj)) {
    if (key.startsWith('$')) continue;
    const path = prefix ? `${prefix}-${key}` : key;
    if (value && typeof value === 'object' && '$value' in value) {
      result[path] = extractValue(value);
    } else if (value && typeof value === 'object' && !('$value' in value)) {
      Object.assign(result, flattenTokens(value, path));
    }
  }
  return result;
}

// Generate CSS
let css = `/* Auto-generated by compile-tokens.js — DO NOT EDIT */\n\n`;

// Dark theme (default via :root)
css += `:root {\n`;
const darkColors = flattenTokens(tokens.color.dark, 'color');
for (const [key, value] of Object.entries(darkColors)) {
  css += `  --${key}: ${value};\n`;
}

const stageColors = flattenTokens(tokens.color.stage, 'color-stage');
for (const [key, value] of Object.entries(stageColors)) {
  css += `  --${key}: ${value};\n`;
}

const spacing = flattenTokens(tokens.space, 'space');
for (const [key, value] of Object.entries(spacing)) {
  css += `  --${key.replace('0.5', '0_5')}: ${value};\n`;
}

const radii = flattenTokens(tokens.radius, 'radius');
for (const [key, value] of Object.entries(radii)) {
  css += `  --${key}: ${value};\n`;
}

const fontSizes = flattenTokens(tokens.fontSize, 'text');
for (const [key, value] of Object.entries(fontSizes)) {
  if (key === 'text-$root') continue;
  css += `  --${key}: ${value};\n`;
}

const lineHeights = flattenTokens(tokens.lineHeight, 'leading');
for (const [key, value] of Object.entries(lineHeights)) {
  css += `  --${key}: ${value};\n`;
}

const fontFamilies = flattenTokens(tokens.fontFamily, 'font');
for (const [key, value] of Object.entries(fontFamilies)) {
  css += `  --${key}: ${value};\n`;
}

const fontWeights = flattenTokens(tokens.fontWeight, 'font-weight');
for (const [key, value] of Object.entries(fontWeights)) {
  css += `  --${key}: ${value};\n`;
}

const motion = flattenTokens(tokens.motion, 'duration');
for (const [key, value] of Object.entries(motion)) {
  css += `  --${key}: ${value};\n`;
}

css += `}\n\n`;

// Light theme override
css += `[data-theme="light"] {\n`;
const lightColors = flattenTokens(tokens.color.light, 'color');
for (const [key, value] of Object.entries(lightColors)) {
  css += `  --${key}: ${value};\n`;
}
css += `}\n`;

mkdirSync(resolve(root, 'src/styles'), { recursive: true });
writeFileSync(resolve(root, 'src/styles/tokens.css'), css);

// Generate TypeScript constants
let ts = `/* Auto-generated by compile-tokens.js — DO NOT EDIT */\n\n`;

function tsEntry(key, value) {
  if (typeof value === 'number') return `  ${JSON.stringify(key)}: ${value},\n`;
  return `  ${JSON.stringify(key)}: ${JSON.stringify(String(value))},\n`;
}

function tsBlock(name, obj, filterFn) {
  let block = `export const ${name} = {\n`;
  for (const [key, value] of Object.entries(obj)) {
    if (filterFn && !filterFn(key)) continue;
    block += tsEntry(key, value);
  }
  block += `} as const;\n\n`;
  return block;
}

ts += tsBlock('darkColors', flattenTokens(tokens.color.dark));
ts += tsBlock('lightColors', flattenTokens(tokens.color.light));
ts += tsBlock('stageColors', flattenTokens(tokens.color.stage));
ts += tsBlock('spacing', flattenTokens(tokens.space));
ts += tsBlock('radius', flattenTokens(tokens.radius));
ts += tsBlock('fontSize', flattenTokens(tokens.fontSize), (k) => k !== '$root');
ts += tsBlock('fontFamily', flattenTokens(tokens.fontFamily));
ts += tsBlock('fontWeight', flattenTokens(tokens.fontWeight));
ts += tsBlock('motion', flattenTokens(tokens.motion));

mkdirSync(resolve(root, 'src/lib'), { recursive: true });
writeFileSync(resolve(root, 'src/lib/tokens.ts'), ts);

console.log('Tokens compiled: src/styles/tokens.css + src/lib/tokens.ts');
