"use client";

import { Suspense, useState } from "react";
import { useSearchParams } from "next/navigation";
import Link from "next/link";
import { useQuery } from "@tanstack/react-query";
import { apiGet } from "@/lib/api";
import { downloadGeneratedDoc } from "@/hooks/use-output-generators";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Skeleton } from "@/components/ui/skeleton";

interface GeneratedDocSummary {
  id: number;
  doc_type: "briefing" | "capture_plan" | "win_themes";
  title: string;
  opportunity_id: string | null;
  capture_id: string | null;
  created_by: string | null;
  created_at: string;
}

const DOC_TYPE_LABELS: Record<string, string> = {
  briefing: "Briefing",
  capture_plan: "Capture Plan",
  win_themes: "Win Themes",
};

function useAllGeneratedDocs(filters: {
  doc_type?: string;
  limit?: number;
  offset?: number;
}) {
  return useQuery({
    queryKey: ["output-generators", "all", filters],
    queryFn: () =>
      apiGet<{ items: GeneratedDocSummary[]; total: number }>(
        "/v3/output-generators",
        {
          doc_type: filters.doc_type,
          limit: String(filters.limit ?? 100),
          offset: String(filters.offset ?? 0),
        },
      ),
  });
}

export default function DocumentsPage() {
  return (
    <Suspense
      fallback={<Skeleton className="h-8 w-64 bg-gda-panel" />}
    >
      <DocumentsContent />
    </Suspense>
  );
}

function DocumentsContent() {
  const searchParams = useSearchParams();
  const filterType = searchParams.get("type") ?? undefined;
  const [typeFilter, setTypeFilter] = useState<string | undefined>(filterType);

  const { data, isLoading, error } = useAllGeneratedDocs({
    doc_type: typeFilter,
    limit: 100,
  });

  const [previewHtml, setPreviewHtml] = useState<string | null>(null);
  const [previewTitle, setPreviewTitle] = useState<string>("");

  const handlePreview = (docId: number, title: string) => {
    setPreviewTitle(title);
    fetch(
      `${process.env.NEXT_PUBLIC_API_BASE ?? "https://gda-v3.csr-llc.tech"}/v3/output-generators/${docId}/html`,
      {
        headers: {
          Authorization: `Bearer ${document.cookie.replace(/(?:(?:^|.*;\s*)token\s*=\s*([^;]*).*$)|^.*$/, "$1") || ""}`,
        },
      },
    )
      .then((r) => r.text())
      .then(setPreviewHtml)
      .catch(() => setPreviewHtml(null));
  };

  return (
    <div className="space-y-4">
      <h1 className="font-mono text-lg font-bold text-foreground">
        Generated Documents
      </h1>
      <p className="text-xs text-muted-foreground">
        Publication-grade deliverables generated by Output Generators (F-313).
      </p>

      {/* Filter tabs */}
      <div className="flex gap-1">
        {[
          { key: undefined, label: "All" },
          { key: "briefing", label: "Briefings" },
          { key: "capture_plan", label: "Capture Plans" },
          { key: "win_themes", label: "Win Themes" },
        ].map((tab) => (
          <button
            key={tab.label}
            type="button"
            onClick={() => setTypeFilter(tab.key)}
            className={`rounded border px-3 py-1 text-xs font-mono transition-colors ${
              typeFilter === tab.key
                ? "border-accent/40 bg-accent/10 text-accent"
                : "border-border text-muted-foreground hover:border-accent/30 hover:text-foreground"
            }`}
          >
            {tab.label}
          </button>
        ))}
      </div>

      {isLoading && (
        <div className="space-y-2">
          <Skeleton className="h-12 w-full bg-gda-panel" />
          <Skeleton className="h-12 w-full bg-gda-panel" />
          <Skeleton className="h-12 w-full bg-gda-panel" />
        </div>
      )}

      {error && (
        <p className="text-xs text-critical">
          {(error as Error).message}
        </p>
      )}

      {data && data.items.length === 0 && (
        <Card className="border-border bg-gda-panel">
          <CardContent className="py-8 text-center">
            <p className="text-sm text-muted-foreground">
              No generated documents yet. Generate a briefing, capture plan, or
              win themes from an opportunity or capture page.
            </p>
          </CardContent>
        </Card>
      )}

      {data && data.items.length > 0 && (
        <Card className="border-border bg-gda-panel">
          <CardHeader className="pb-2">
            <CardTitle className="font-mono text-xs text-muted-foreground uppercase">
              {data.total} Document{data.total !== 1 ? "s" : ""}
            </CardTitle>
          </CardHeader>
          <CardContent className="space-y-1">
            {data.items.map((doc) => (
              <div
                key={doc.id}
                className="flex items-center justify-between rounded border border-border bg-white px-4 py-2.5 text-xs hover:border-accent/30 transition-colors"
              >
                <div className="flex items-center gap-3 min-w-0">
                  <span className="rounded border border-accent/20 bg-accent/5 px-2 py-0.5 text-[11px] font-mono text-accent whitespace-nowrap">
                    {DOC_TYPE_LABELS[doc.doc_type] ?? doc.doc_type}
                  </span>
                  <span className="text-foreground font-medium truncate">
                    {doc.title}
                  </span>
                </div>
                <div className="flex items-center gap-3 shrink-0">
                  {doc.opportunity_id && (
                    <Link
                      href={`/opportunities?id=${doc.opportunity_id}`}
                      className="text-accent hover:underline text-[11px]"
                    >
                      Opportunity
                    </Link>
                  )}
                  {doc.capture_id && (
                    <Link
                      href={`/capture?id=${doc.capture_id}`}
                      className="text-accent hover:underline text-[11px]"
                    >
                      Capture
                    </Link>
                  )}
                  <button
                    type="button"
                    onClick={() => handlePreview(doc.id, doc.title)}
                    className="text-accent hover:underline text-[11px]"
                  >
                    Preview
                  </button>
                  <button
                    type="button"
                    onClick={() => downloadGeneratedDoc(doc.id, doc.title)}
                    className="text-accent hover:underline text-[11px]"
                  >
                    Download
                  </button>
                  <span className="text-muted-foreground text-[11px] font-mono whitespace-nowrap">
                    {new Date(doc.created_at).toLocaleDateString()}
                  </span>
                </div>
              </div>
            ))}
          </CardContent>
        </Card>
      )}

      {previewHtml && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50">
          <div className="w-full max-w-4xl max-h-[90vh] flex flex-col rounded-lg border border-border bg-white shadow-xl">
            <div className="flex items-center justify-between border-b border-border px-4 py-3">
              <span className="font-mono text-sm text-foreground">
                {previewTitle}
              </span>
              <button
                type="button"
                onClick={() => setPreviewHtml(null)}
                className="rounded border border-border px-2 py-0.5 text-xs text-muted-foreground hover:text-foreground"
              >
                Close
              </button>
            </div>
            <div className="flex-1 overflow-auto p-4">
              <iframe
                srcDoc={previewHtml}
                title="Document Preview"
                className="w-full h-full min-h-[600px] border-0"
                sandbox="allow-same-origin"
              />
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
