/* Auto-generated by compile-tokens.js — DO NOT EDIT */

export const darkColors = {
  "canvas": "#0B0D0F",
  "surface": "#13161A",
  "surface-raised": "#1A1E23",
  "border": "#2A2F36",
  "border-strong": "#3D434C",
  "ink-primary": "#E6E8EB",
  "ink-muted": "#9AA0A8",
  "ink-dim": "#6B7079",
  "accent": "#01696F",
  "accent-hover": "#017F86",
  "accent-pressed": "#015C61",
  "critical": "#A12C7B",
  "critical-hover": "#B8338E",
  "success": "#3FA66B",
  "success-hover": "#4DBD7A",
  "warning": "#C48A1E",
  "warning-hover": "#D69B2F",
} as const;

export const lightColors = {
  "canvas": "#F7F6F2",
  "surface": "#FFFFFF",
  "surface-raised": "#FFFFFF",
  "border": "#D4D1CA",
  "border-strong": "#B8B5AE",
  "ink-primary": "#28251D",
  "ink-muted": "#7A7974",
  "ink-dim": "#A3A09A",
  "accent": "#01696F",
  "accent-hover": "#017F86",
  "accent-pressed": "#015C61",
  "critical": "#A12C7B",
  "critical-hover": "#B8338E",
  "success": "#2E8B57",
  "success-hover": "#3A9D66",
  "warning": "#B45309",
  "warning-hover": "#C5641A",
} as const;

export const stageColors = {
  "0": "#6B7079",
  "1": "#9AA0A8",
  "2": "#01696F",
  "3": "#01696F",
  "4": "#C48A1E",
  "5": "#C48A1E",
  "6": "#3FA66B",
} as const;

export const spacing = {
  "0": "0px",
  "1": "4px",
  "2": "8px",
  "3": "12px",
  "4": "16px",
  "5": "20px",
  "6": "24px",
  "8": "32px",
  "10": "40px",
  "12": "48px",
  "16": "64px",
  "0.5": "2px",
} as const;

export const radius = {
  "sm": "4px",
  "md": "6px",
  "full": "999px",
} as const;

export const fontSize = {
  "xs": "0.75rem",
  "sm": "0.8125rem",
  "base": "1rem",
  "md": "1.067rem",
  "lg": "1.2rem",
  "xl": "1.333rem",
  "2xl": "1.6rem",
  "3xl": "2rem",
} as const;

export const fontFamily = {
  "ui": "'Inter', system-ui, -apple-system, sans-serif",
  "numeric": "'Inter', system-ui, sans-serif",
  "mono": "'JetBrains Mono', ui-monospace, monospace",
} as const;

export const fontWeight = {
  "regular": 400,
  "medium": 500,
  "semibold": 600,
  "bold": 700,
} as const;

export const motion = {
  "reveal": "120ms",
  "state": "80ms",
  "hover": "0ms",
} as const;

